app = "utility-fiy"
primary_region = "ord"

[build]

[env]
  APP_ENV = "production"
  APP_DEBUG = "false"
  DB_CONNECTION = "sqlite"
  DB_DATABASE = "/data/database.sqlite"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[mounts]]
  source = "data"
  destination = "/data"

[[statics]]
  guest_path = "/app/public"
  url_prefix = "/"
